name: Deploy SvelteKit to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

# 2 jobs: build the SvelteKit static site, and deploy the built site to GitHub Pages
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repo code
      - uses: actions/checkout@v4

      # Use the Node version defined in .nvmrc
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm # cache node_modules for faster builds

      - name: Install dependencies
        run: npm ci # install dependencies using lock file

      - name: Security audit
        run: npm audit --audit-level=high # low and moderate vulnerabilities wont fail CI

      - name: Install Playwright browsers for e2e tests
        run: npx playwright install --with-deps

      - name: Run tests
        run: npm test

      # Build the SvelteKit project
      - name: Build project
        run: npm run build

      # Upload build output as artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build # SvelteKit static output folder

  deploy:
    needs: build # make the build artifact available here in deploy job
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }} # just a convenience, adds page url to action summary page

    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
